### ISSUE TITLE
CollectorComposite bug ?

### ISSUE THREAD

**Issue by benkrikler** [shane-breeze/atuproot#31]
Our nightly build failed yesterday morning and it looks like an issue in atuproot-0.1.10.  https://gitlab.cern.ch/fast-hep/public/fast_cms_public_tutorial/-/jobs/3531295.
I've pinned fast-carpenter to a previous version of atuproot (0.1.7) for now, where we didn't see this issue.

**Comment by shane-breeze** [comment]
Yes, I added a bug in CollectorComposite. It's fixed in v0.1.11 - which I've tested on my side

**Comment by benkrikler** [comment]
Ah cool, thanks.  I'll close this for now then, and update things on my side.
